### ISSUE TITLE
 "Camera is not enabled. Try running 'sudo raspi-config' "

### ISSUE THREAD

**Issue by natlownes** [resin-io-projects/resin-rpi-python-picamera#1]
I gave this guy a shot and after a little bit of poking around I realized on the host, in `/boot/config.txt` I had to set `gpu_mem=128` (or > 128) and make sure the RPi model specific settings weren't overriding that setting.  Another /boot/config.txt reference mentioned setting `start_x=1` to enable the camera.

Neither of these seemed to work and in the resin.io dashboard I'm getting:

```
[system] Starting application registry.resin.io/camtest/020c27dee97be78d0ae1e43db159268611c02039
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
Traceback (most recent call last):
File "/app/demo.py", line 22, in <module>
with picamera.PiCamera() as camera:
File "/usr/local/lib/python2.7/dist-packages/picamera/camera.py", line 419, in __init__
self.STEREO_MODES[stereo_mode], stereo_decimate)
File "/usr/local/lib/python2.7/dist-packages/picamera/camera.py", line 457, in _init_camera
"Camera is not enabled. Try running 'sudo raspi-config' "
picamera.exc.PiCameraError: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.
```

Am I missing something here or is this not possible?

**Comment by shaunmulligan** [comment]
Hi there. I just pushed this project to a freshly provisioned Raspberry pi B+ on resin.io, basically just `git clone` and then `git push resin master`. However, I couldn't reproduce your error. Could you give me a bit more detail about your setup. Which version of the RPi are you using, and how are you powering it? If you look at the troubleshooting secion of http://elinux.org/Rpi_Camera_Module you see that this error is sometimes caused by an under powered power supply.

It is also worth double checking your camera module connection. You shouldn't have to mess around with anything in config.txt, nor need to run raspi-config or rpi-update. All of this is handled in the Dockerfile.

**Comment by natlownes** [comment]
Awesome, thanks.  

After a bit more poking around this morning, I realized there are a number of conditions that can toss this error; low power, busted camera, etc.

I'm positive one of these is my issue.  Thanks so much for your time

**Comment by kabilramar** [comment]
how to check whether my picamera is low powered
